### ISSUE TITLE
tinyfiledialogs doesn't support glibc version that ubuntu 20.04 uses

### ISSUE THREAD

**Issue by mariomadproductions** [shibbo/Fushigi#26]
```
user@linuxpc1:~/downloads/Fushigi/Fushigi/bin/Release/net8.0/linux-x64$ DOTNET_ROOT=~/opt/dotnet-8 ./Fushigi
--
  | Unhandled exception. System.DllNotFoundException: Unable to load shared library 'tinyfiledialogs' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
  | /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/downloads/Fushigi/Fushigi/bin/Release/net8.0/linux-x64/tinyfiledialogs.so)
  | /home/user/opt/dotnet-8/shared/Microsoft.NETCore.App/8.0.0-rc.2.23479.6/tinyfiledialogs.so: cannot open shared object file: No such file or directory
  | /home/user/downloads/Fushigi/Fushigi/bin/Release/net8.0/linux-x64/libtinyfiledialogs.so: cannot open shared object file: No such file or directory
  | /home/user/opt/dotnet-8/shared/Microsoft.NETCore.App/8.0.0-rc.2.23479.6/libtinyfiledialogs.so: cannot open shared object file: No such file or directory
  | /home/user/downloads/Fushigi/Fushigi/bin/Release/net8.0/linux-x64/tinyfiledialogs: cannot open shared object file: No such file or directory
  | /home/user/opt/dotnet-8/shared/Microsoft.NETCore.App/8.0.0-rc.2.23479.6/tinyfiledialogs: cannot open shared object file: No such file or directory
  | /home/user/downloads/Fushigi/Fushigi/bin/Release/net8.0/linux-x64/libtinyfiledialogs: cannot open shared object file: No such file or directory
  | /home/user/opt/dotnet-8/shared/Microsoft.NETCore.App/8.0.0-rc.2.23479.6/libtinyfiledialogs: cannot open shared object file: No such file or directory
  |  
  | at TinyDialogsNet.Dialogs.tinyfd_messageBox(String title, String message, String dialogType, String iconType, Int32 defaultButton)
  | at TinyDialogsNet.Dialogs.MessageBox(MessageBoxButtons buttons, MessageBoxIconType iconType, MessageBoxDefaultButton defaultButton, String title, String message)
  | at Fushigi.RomFS.SetRoot(String root) in /home/user/downloads/Fushigi/Fushigi/RomFS.cs:line 15
  | at Fushigi.util.UserSettings.Load() in /home/user/downloads/Fushigi/Fushigi/util/UserSettings.cs:line 36
  | at Program.<Main>$(String[] args) in /home/user/downloads/Fushigi/Fushigi/Program.cs:line 5
  | Aborted (core dumped)
```

Ubuntu 20.04 is one of the ubuntu LTS builds, and some software still requires it over 22.04, so I'd say it'd be a good idea to support it.

**Comment by shibbo** [comment]
closing as we are no longer using TinyFileDialogs
